workflows:
  kmm-default:
    name: Kotlin Multiplatform Mobile (iOS+Android)
    max_build_duration: 60

    instance_type: mac_mini_m2

    environment:
      xcode: 15.4
      vars:
        XCODE_SCHEME: iosApp
        IOS_DEPLOYMENT_TARGET: "16.0"
        GRADLE_OPTS: "-Xmx4g -Dorg.gradle.unsafe.configuration-cache=false"

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: true

    scripts:
      - name: Prepare macOS
        script: |
          brew update
          brew install cocoapods

      - name: Gradle clean
        script: ./gradlew clean

      - name: Build Android App
        script: ./gradlew :androidApp:assembleRelease -x lintVitalRelease

      - name: Generate dummy iOS framework for CocoaPods
        script: ./gradlew :shared:generateDummyFramework

      - name: Install CocoaPods
        script: |
          cd iosApp
          pod repo update
          pod install --verbose

      - name: Build iOS App
        script: |
          cd iosApp
          xcodebuild \
            -workspace iosApp.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -sdk "iphonesimulator" \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            -configuration Release \
            clean build

    artifacts:
      - shared/build/**/release/shared.framework
      - iosApp/build/Release-iphonesimulator/*.app
      - androidApp/app/build/outputs/**/*.apk
      - /Users/builder/Library/Developer/Xcode/DerivedData/**/*.app
      - app/build/outputs/apk/debug/app-debug.apk