workflows:
  kmm-default:
    name: Kotlin Multiplatform Mobile (iOS+Android)
    max_build_duration: 60 # em minutos

    environment:
      vars:
        IOS_SDK: iphonesimulator14.5
        SIMULATOR_NAME: "iPhone 12"
        XCODE_SCHEME: iosApp
        IOS_DEPLOYMENT_TARGET: "14.1"

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: true

    scripts:
      - name: Prepare macOS
        script: |
          brew update
          brew install cocoapods

      - name: Gradle clean
        script: ./gradlew clean

      - name: Build Android App
        script: ./gradlew :androidApp:assembleRelease -x lintVitalRelease

      - name: Build iOS Frameworks
        script: |
          # força não usar configuration cache e força refazer tudo
          ./gradlew --no-configuration-cache --rerun-tasks \
            :shared:linkReleaseFrameworkIosX64 \
            :shared:linkReleaseFrameworkIosArm64

      - name: Install CocoaPods
        script: |
          cd iosApp
          pod repo update
          pod install --verbose

      - name: Build iOS App
        script: |
          cd iosApp
          xcodebuild \
            -workspace iosApp.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -sdk "$IOS_SDK" \
            -destination "platform=iOS Simulator,name=$SIMULATOR_NAME" \
            -configuration Release \
            clean build

    artifacts:
      - shared/build/**/release/shared.framework
      - iosApp/build/Release-iphonesimulator/*.app
      - androidApp/app/build/outputs/**/*.apk