workflows:
  kmm-default:
    name: Kotlin Multiplatform Mobile (iOS+Android)
    max_build_duration: 60 # em minutos

    # 1) variáveis de ambiente
    environment:
      vars:
        IOS_SDK: iphonesimulator14.5
        SIMULATOR_NAME: "iPhone 12"
        XCODE_SCHEME: iosApp
        IOS_DEPLOYMENT_TARGET: "14.1"

    # 2) eventos que disparam o build
    trigger:
      - push
      - pull_request

    # 3) passos de build
    scripts:
      - name: Prepare macOS
        script: |
          brew update
          brew install cocoapods

      - name: Gradle clean
        script: ./gradlew clean

      - name: Build Android App
        script: ./gradlew :androidApp:assembleRelease

      - name: Build iOS Frameworks
        script: |
          ./gradlew :shared:linkReleaseFrameworkIosX64
          ./gradlew :shared:linkReleaseFrameworkIosArm64

      - name: Install CocoaPods
        script: |
          cd iosApp
          pod repo update
          pod install --verbose

      - name: Build iOS App
        script: |
          cd iosApp
          xcodebuild \
            -workspace iosApp.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -sdk "$IOS_SDK" \
            -destination "platform=iOS Simulator,name=$SIMULATOR_NAME" \
            -configuration Release \
            clean build

    # 4) artefatos que você quer baixar
    artifacts:
      - shared/build/**/release/shared.framework
      - iosApp/build/Release-iphonesimulator/*.app
      - androidApp/app/build/outputs/**/*.apk

    # 5) (opcional) notificações
    # notifications:
    #   slack:
    #     webhook_url: Encrypted(...)
    #     channel: "#ci-builds"
    #     on_failure: true

